habit_tracker/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import HabitViewSet

app_name = 'api'

API_VERSION = 'v1'

router = DefaultRouter()
router.register(r'habits', HabitViewSet, basename='habit')
# router.register('groups', GroupViewSet, basename='group')
# router.register(r'^habits/(?P<habit_id>\d+)/comments',
#                 CommentViewSet, basename='comment')
# router.register('follow', FollowViewSet, basename='follow')

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]
# urlpatterns = [
#     path(f'{API_VERSION}/', include(router.urls)),
#     path(f'{API_VERSION}/', include('djoser.urls')),
#     path(f'{API_VERSION}/', include('djoser.urls.jwt')),
# ]

habit_tracker/habit_tracker/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('habits.urls', namespace='habits')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

habit_tracker/habits/urls.py
from django.urls import path

from . import views

app_name = 'habits'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'complete-habit/<int:habit_id>/',
        views.complete_habit,
        name='complete-habit'
    ),
    path(
        'habit-chart/',
        views.habit_chart,
        name='habit-chart'
    ),
    path(
        'habits/<int:habit_id>/detail/',
        views.habit_detail,
        name='habit-detail'
    ),
    path(
        'habits/<int:habit_id>/edit/',
        views.habit_edit, name='habit-edit'
    ),
    path(
        'habits/<int:habit_id>/delete/',
        views.habit_delete,
        name='habit-delete'
    ),
    path(
        'daily-habits/<str:date>/',
        views.habit_list,
        name='daily-habits'
    ),
]

habit_tracker/habits/models.py
from datetime import date
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Habit(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Привычка',
        help_text='Укажите название привычки'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='habits',
        verbose_name='Автор',
    )
    completed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Привычка'
        verbose_name_plural = 'Привычки'

    def __str__(self):
        return self.title


class DailyHabit(models.Model):
    habit = models.ForeignKey(
        Habit,
        on_delete=models.CASCADE,
        related_name='daily_habits',
        verbose_name='Привычка',
    )
    date = models.DateField(
        default=date.today,
        verbose_name='Дата'
    )
    completed = models.BooleanField(
        default=False,
        verbose_name='Выполнено'
    )

    class Meta:
        verbose_name = 'Ежедневная привычка'
        verbose_name_plural = 'Ежедневные привычки'

    def __str__(self):
        return f'{self.date}: {self.habit} - {self.completed}'

habit_tracker/habits/forms.py
from django import forms
from .models import Habit


class HabitForm(forms.ModelForm):
    class Meta:
        model = Habit
        fields = ['title']


class HabitDetailForm(forms.ModelForm):
    class Meta:
        model = Habit
        fields = ['title']

habit_tracker/habits/views.py
import base64
from datetime import date
import io

import matplotlib
import matplotlib.pyplot as plt

from django.db import models
from django.shortcuts import get_object_or_404, redirect, render

from .forms import HabitDetailForm, HabitForm
from .models import DailyHabit, Habit

matplotlib.use('Agg')


def index(request):
    current_date = str(date.today())
    habits = DailyHabit.objects.filter(date=current_date,
                                       habit__author=request.user)
    if request.method == 'POST':
        form = HabitForm(request.POST)
        if form.is_valid():
            habit = form.save(commit=False)
            habit.author = request.user
            habit.save()
            daily_habit = DailyHabit.objects.create(habit=habit)
            daily_habit.save()
            return redirect('habits:index')
    else:
        form = HabitForm()
    context = {
        'form': form,
        'habits': habits,
        'current_date': current_date,
    }
    return render(request, 'index.html', context)


def complete_habit(request, habit_id):
    habit = DailyHabit.objects.get(id=habit_id, habit__author=request.user)
    if request.method == 'POST':
        habit.completed = not habit.completed
        habit.save()
    return redirect('habits:index')


def habit_list(request, date):
    habit_date = date
    habits = DailyHabit.objects.filter(date=habit_date,
                                       habit__author=request.user)
    context = {
        'habits': habits,
        'habit_date': habit_date
    }
    return render(request, 'habit-list.html', context)


def habit_detail(request, habit_id):
    habit = get_object_or_404(
        Habit.objects.select_related('author'), pk=habit_id)
    form = HabitDetailForm(request.POST or None, instance=habit)
    context = {
        'habit': habit,
        'form': form
    }
    return render(request, 'habit-detail.html', context)


def habit_edit(request, habit_id):
    habit = get_object_or_404(Habit.objects.select_related('author'),
                              pk=habit_id)
    if habit.author == request.user:
        form = HabitForm(request.POST or None,
                         instance=habit)
        if form.is_valid():
            form.save()
            return redirect('habits:habit-detail', habit.id)
        return render(request, 'index.html', {'form': form})
    return redirect('habits:habit-detail', habit.id)


def habit_delete(request, habit_id):
    habit = get_object_or_404(Habit, pk=habit_id)
    if habit.author == request.user:
        habit.delete()
        return redirect('habits:index')
    return redirect('habits:index')


def habit_chart(request):
    habits = DailyHabit.objects.filter(habit__author=request.user)
    # Находим количество выполненных привычек для
    #  каждого дня только для текущего пользователя
    completion_data = (habits.values('date')
                       .annotate(total_completed=models.Count(
                           'id', filter=models.Q(completed=True)
                        ))
                       .order_by('date'))
    # Создаем списки с данными для построения графика
    dates = [item['date'].strftime('%Y-%m-%d') for item in completion_data]
    completed = [item['total_completed'] for item in completion_data]
    # Создаем график
    fig, ax = plt.subplots()
    ax.plot(dates, completed)
    # Настройка осей x и y
    ax.set_xlabel('Дата')
    ax.set_ylabel('Количество выполненных привычек')
    # Поворот значений на оси x для лучшей читаемости
    plt.xticks(rotation=0)
    # Задаем значения оси y
    plt.yticks(range(0, Habit.objects.select_related('author').count() + 1))
    # Добавляем отметки с количеством выполненных
    # привычек только для текущего пользователя
    for i in range(len(dates)):
        completed_habits_count = habits.filter(date=dates[i],
                                               completed=True).count()
        if completed_habits_count > 0:
            ax.annotate(str(completed_habits_count),
                        (dates[i], completed_habits_count),
                        ha='center', va='bottom')
    # Конвертируем график в изображение
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image = buffer.getvalue()
    buffer.close()
    # Кодируем изображение и передаем его в контекст шаблона
    image_base64 = base64.b64encode(image).decode('utf-8')
    context = {
        'image': image_base64
    }
    # Возвращаем шаблон с контекстом
    return render(request, 'habit-chart.html', context)

habit_tracker/habits/templates/form.html
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            {{ card_header }}
        </div>

        <div class="card-body">
          {{ card_body }}

          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post" enctype="multipart/form-data" {{ action }}>
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
          
            {% if not form.button %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {{ button }}
                </button>
              </div>
            {% endif %} 
          </form>
        </div>
      </div>
    </div>
  </div>

habit_tracker/habits/templates/habit-chart.html
<!DOCTYPE html>
<html>
  
{% load static %}
{% load user_filters %}

<head>
    <meta charset="utf-8">
    <title>Habit Tracker</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                <h1 class="text-center">Habit Tracker</h1>
              </div>

            <img src="data:image/png;base64,{{ image }}" alt="Habit Chart">

            <div class="row justify-content-center">
            <div class="col-md-8 p-5">
        <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary"><a href="{% url 'habits:index' %}">На главную</a></button>
        </div>
     </div>
   </div>

</body>
</html>

habit_tracker/habits/templates/habit-detail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Habit Tracker</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <br>
    <h1 style="text-align: center;">{{ habit.title }}</h1>
    <div class="shadow-sm p-3 bg-white">
        <ul>
            <li>Автор: {{ habit.author }}</li>
            <li>Дата начала привычки: {{ habit.created|date:"d E Y" }}</li>
        </ul>
    </div>

    {% with card_header='Редактировать привычку' button='Сохранить' %}
    <form method="post" action="{% url 'habits:habit-edit' habit.id %}">
        {% include 'form.html' %}
    {% endwith %}
    </form>

    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <form method="POST" action="{% url 'habits:habit-delete' habit.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
            </form>
    
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary"><a href="{% url 'habits:index' %}">На главную</a></button>
            </div>
        </div>
    </div>

</body>
</html>

habit_tracker/habits/templates/habit-list.html
<!--'habit-list.html'-->
<!DOCTYPE html>
<html>
  
{% load static %}
{% load user_filters %}

<head>
    <meta charset="utf-8">
    <title>Habit Tracker</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <!-- Список привычек -->

    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                <h1 class="text-center">Habit Tracker</h1>
                <h6 class="text-center">Дата: {{ habits.0.date }}</h6>
              </div>
              <div class="card-body">
                <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th>Привычка</th>
                      <th>Выполнено {{ date_obj }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for habit in habits %}
                      <tr>
                        <td>{{ habit.habit.title  }}</a></td>
                        <td>
                          
                              {% if habit.completed %}🟩{% else %}⬜️{% endif %}
                            </button>
                          </form>
                        </td>
                      </tr>
                    {% empty %}
                      <tr>
                        <td colspan="2">Нет привычек</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-8 p-5">     
            <a href="{% url 'habits:daily-habits' date=habit_date|previous_date %}">Предыдущий день</a>
                <div class="d-flex justify-content-end">      
                    <a href="{% url 'habits:daily-habits' date=habit_date|next_date %}">Следующий день</a>
               </div>
         </div>
       </div>

        <div class="row justify-content-center">
         <div class="col-md-8 p-5">
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary"><a href="{% url 'habits:index' %}">На главную</a></button>
            </div>
          </div>
        </div>

</body>
</html>

habit_tracker/habits/templates/index.html
<!--'index.html'-->
<!DOCTYPE html>
<html>
  
{% load static %}
{% load user_filters %}

<head>
    <meta charset="utf-8">
    <title>Habit Tracker</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <!-- Список привычек -->

    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                <h1 class="text-center">Habit Tracker</h1>
                <h6 class="text-center">Дата: {{ habits.0.date }}</h6>
              </div>
              <div class="card-body">
                <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th>Привычка</th>
                      <th>Выполнено сегодня</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for habit in habits %}
                      <tr>
                        <td><a href="{% url 'habits:habit-detail' habit.habit.id %}">{{ habit.habit.title  }}</a></td>
                        <td>
                          <form method="POST" action="{% url 'habits:complete-habit' habit.id %}">
                            {% csrf_token %}
                            {{ complete_form.as_p }}
                            <button type="submit" class="btn">
                              {% if habit.completed %}🟩{% else %}⬜️{% endif %}
                            </button>
                          </form>
                        </td>
                      </tr>
                    {% empty %}
                      <tr>
                        <td colspan="2">Нет привычек</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">     
          <a href="{% url 'habits:daily-habits' date=current_date|previous_date %}">Предыдущий день</a><br>
      
          <a href="{% url 'habits:habit-chart' %}">График выполнения привычек</a>
         </div>
       </div>
      
  
      

 <!-- Форма для добавления привычки -->
{% with card_header='Добавить новую привычку' button='Добавить' %}
 {% include 'form.html' %}
{% endwith %}

</body>
</html>